- name: Run cert script # noqa: yaml
  command: "/usr/bin/certbot --nginx -n --agree-tos --redirect --expand --email {{ email }} --domains {{ domain }}"
  changed_when: true

- name: Keep certs updated
  cron:
    name: update certs
    state: present
    special_time: monthly
    job: "certbot --nginx renew"
