- name: Copy config file
  copy:
    src: "nginx.conf"
    dest: "/etc/nginx/nginx.conf"
    mode: 0644

- name: Copy hardened defaults
  copy:
    src: "harden.conf"
    dest: "/etc/nginx/conf.d/harden.conf"
    mode: 0644

- name: Ensure HTTP port is available
  shell:
    cmd: |
      set +o pipefail
      sudo lsof -ti:{{ item }} | xargs -r sudo kill
    executable: /bin/bash
  with_items:
    - "{{ ports.http }}"
    - "{{ ports.https }}"
  changed_when: true

- name: Enable and restart nginx
  service:
    name: nginx
    enabled: true
    state: restarted
