- name: Install nginx and certbot
  import_tasks: install.yaml

- name: Configure servers
  import_tasks: servers.yaml

- name: Configure nginx
  import_tasks: config.yaml

- name: Create certs and keep them updated
  import_tasks: certs.yaml
