---
- name: Create user
  hosts: vps
  remote_user: root
  gather_facts: no
  vars_files:
    - .env.yml
  roles:
    - role: user
      tags:
        - user

- name: Server setup
  hosts: vps
  remote_user: "{{ username }}"
  vars_files:
    - .env.yml
  roles:
    - role: harden
      become: true
      tags:
        - harden
        - sec

    - role: housekeeping
      become: true
      tags:
        - housekeeping

    - role: fail2ban
      become: true
      tags:
        - fail2ban
        - sec

    - role: nginx
      become: true
      tags:
        - nginx

    - role: dmitriaronson.com
      become: true
      tags:
        - website
