- name: Password-less sudo for {{ username }}
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Setup ssh for {{ username }}
  authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('file', ssh_key + '.pub' | default('~/.ssh/id_rsa.pub')) }}"
