- name: Update system
  become: true
  package:
    update_cache: true
    upgrade: true

- name: Install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"
