- name: Install packages
  import_role:
    name: common_roles/install_latest
  vars:
    packages:
      - "docker"
      - "docker-compose"

- name: Setup log rotation
  become: true
  copy:
    content: |
      {
        "log-opts": {
          "max-size": "10m",
          "max-file": "5"
        }
      }
    dest: /etc/docker/daemon.json

- name: Start and enable docker
  become: true
  systemd:
    name: docker
    daemon_reload: true
    state: started
    enabled: true
