name: Deploy dmitriaronson.com

on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-dmitriaronsoncom]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ vars.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Run Ansible playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
          ANSIBLE_USERNAME: ${{ secrets.ANSIBLE_USERNAME }}
          ANSIBLE_DOMAIN: ${{ secrets.ANSIBLE_DOMAIN }}
          WEBSITE_DOMAIN: dmitriaronson.com
          EMAIL: ${{ secrets.EMAIL }}
          SSH_KEY: "~/.ssh/id_ed25519"
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        run: |
          cp .env-sample.yaml .env
          ansible-playbook playbook.yaml -u ${{ vars.VPS_USERNAME }} --tags website